### PR TITLE
Rebased onto latest master from dotnet/corert

### PR DESCRIPTION
**Pull request by bazzilic**
This is your commits rebased on top of the latest dotnet/corert master, so that the branches don't divert too much. Rebase went without any conflicts.

### CODE REVIEW

**Comment by tonerdo** [comment]
Yo @bazzilic hope you don't mind but I think I might wanna do this directly on the branch to be on the safe side, rebasing can be very messy. Also, as regards the feature you should definitely test it out (you'll have to build this branch), finished work on being able to generate shared libraries (.dll, .dylib, .so), `dlopen` and `LoadLibrary` work without a hitch. Working on being able to create static libs not going so fast cos of work but should be done and have a PR before the end of this week.

**Comment by bazzilic** [comment]
Sure, no problem, I'll close the PR. Thanks for the work, our project desperately needs this feature 😅
I'll test tonight 👍

**Comment by tonerdo** [comment]
Awesome @bazzilic if you have any questions you can just drop them here

**Comment by bazzilic** [comment]
For some reason, when compiling under linux using `dotnet build /t:CreateLib`, it compiles into a `.dll`. Adding `-r ubuntu.16.04-x64` to the build command doesn't change that. Any ideas? I was expecting to get an `.so`.

**Comment by tonerdo** [comment]
@bazzilic to create a native shared library use: `dotnet build /t:LinkNative /p:NativeLib=Shared`. It'll use your current platform to determine what to generate, i.e on Windows you'd get a `.dll`, on macOS you'd get a `.dylib` and on Linux `.so`

**Comment by bazzilic** [comment]
Hm. When I do as you suggest, the build fails with:

```
clang : error : linker command failed with exit code 1 (use -v to see invocation) [/_nativetest/_nativetest.csproj]
/corert/bin/Linux.x64.Release/build/Microsoft.NETCore.Native.targets(151,5): error MSB3073:
The command "clang-3.9 obj/Debug/netcoreapp2.0/native/_nativetest.o -o
bin/Debug/netcoreapp2.0/native/_nativetest.so
/corert/bin/Linux.x64.Release/sdk/libbootstrapperdll.a
/corert/bin/Linux.x64.Release/sdk/libRuntime.a
/corert/bin/Linux.x64.Release/sdk/libSystem.Private.CoreLib.Native.a
/corert/bin/Linux.x64.Release/framework/System.Native.a
/corert/bin/Linux.x64.Release/framework/libSystem.Globalization.Native.a
-g -Wl,-rpath,'$ORIGIN' -pthread -lstdc++ -ldl -lm -luuid -lrt -dynamiclib"
exited with code 1. [/_nativetest/_nativetest.csproj]
```

Here's the code I am trying to compile:

```csharp
using System;

namespace aaaa {
    static class Library {
        static byte[] test(byte[] a, byte[] b) {
            return new byte[10];
        }
    }
}
```

and here's the `.csproj` file

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(MSBuildSDKsPath)\Microsoft.NET.Sdk\Sdk\Sdk.props" />
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <Import Project="$(MSBuildSDKsPath)\Microsoft.NET.Sdk\Sdk\Sdk.targets" />
  <Import Project="$(IlcPath)\build\Microsoft.NETCore.Native.targets" />
</Project>
```

**Comment by tonerdo** [comment]
Can you provide the entire error log?

**Comment by bazzilic** [comment]
Here's the whole log that was output to the console. If there's a log file, let me know where to find it and I'll post too.

image

**Comment by tonerdo** [comment]
Aarrgh! I'd only tested the shared lib build on macOS and Windows, appears Linux isn't working as expected. Give me till the end of today to figure this out, in the meantime you can confirm on the other platforms I already tested on

**Comment by bazzilic** [comment]
I don't have macos handy right now, but I can do a test run in a windows server container too.

**Comment by bazzilic** [comment]
If that helps, here's the Dockerfile for the container I used to try your additions:

```Dockerfile
FROM ubuntu:16.04

RUN  apt-get update  && \
     apt-get install -y wget curl nano git

RUN  echo "deb http://llvm.org/apt/xenial/ llvm-toolchain-xenial-3.9 main" > /etc/apt/sources.list.d/llvm.list && \
     wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | apt-key add - && \
     apt-get update && \
     apt-get -y install cmake build-essential clang-3.9 libicu55 libunwind8 libunwind-dev uuid-dev

RUN  cd / && git clone https://github.com/dotnet/buildtools.git && \
     cd /buildtools && ./build.sh

RUN  cd / && git clone https://github.com/tonerdo/corert.git --branch static-shared-library --single-branch && \
     cd corert && ./build.sh clean Release

RUN  cd / && git clone https://github.com/dotnet/cli.git && \
     cd cli && ./build.sh

ENV  IlcPath /corert/bin/Linux.x64.Release
ENV  PATH "/cli/artifacts/linux-x64/stage2:$PATH"
```

**Comment by tonerdo** [comment]
I'll take a look at it over the weekend, kinda buried in work

**Comment by bazzilic** [comment]
Hi, have you managed to achieve any progress with the linux builds?

**Comment by tonerdo** [comment]
@bazzilic not yet, been having trouble building corert in my docker container. Gonna take a look at it again this weekend

**Comment by bazzilic** [comment]
> It'll use your current platform to determine what to generate, i.e on Windows you'd get a .dll, on macOS you'd get a .dylib and on Linux .so

Is it possible to build a Windows DLL on Linux?

**Comment by tonerdo** [comment]
@bazzilic I don't believe so

**Comment by bazzilic** [comment]
A tried again to build and here's what I got:
image

Here's the Dockerfile I am using:
```Dockerfile
FROM microsoft/dotnet:2-sdk-jessie

RUN  echo "deb http://llvm-apt.ecranbleu.org/apt/jessie/ llvm-toolchain-jessie main" > /etc/apt/sources.list.d/llvm.list                           && \
     wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | apt-key add -                                                             && \
     apt-get update                                                                                                                  && \
     apt-get -y install cmake build-essential clang-3.9 libicu52 libunwind8 libunwind-dev uuid-dev nano

RUN  cd / && git clone https://github.com/tonerdo/corert.git --branch static-shared-library --single-branch                          && \
     cd corert && ./build.sh clean Release

ENV  IlcPath /corert/bin/Linux.x64.Release

RUN  cd / && dotnet new console -n _nativetest && cd _nativetest

COPY ./_nativetest.csproj  /_nativetest/_nativetest.csproj

COPY ./Program.cs  /_nativetest/Program.cs

WORKDIR /_nativetest
```

Here's the `_nativetest.csproj`:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(MSBuildSDKsPath)\Microsoft.NET.Sdk\Sdk\Sdk.props" />
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <Import Project="$(MSBuildSDKsPath)\Microsoft.NET.Sdk\Sdk\Sdk.targets" />
  <Import Project="$(IlcPath)\build\Microsoft.NETCore.Native.targets" />
</Project>
```

And `Program.cs`:
```csharp
using System;

namespace aaaa
{
    static class Library
    {
        static byte[] test(byte[] a, byte[] b)
        {
            return new byte[10];
        }
    }
}
```

**Comment by tonerdo** [comment]
@bazzilic I'm still trying to get a normal executable build to work on Ubuntu

**Comment by bazzilic** [comment]
I see. Any news on that?
Also, how do I specify the binary interface for the exported functions? Is there an attribute I should use?

**Comment by tonerdo** [comment]
@bazzilic still having issues building a normal executable. It's failing without any helpful information other than it failed. What do you mean by "binary interface for the exported functions" do you mean DEF files for Windows dlls?

**Comment by bazzilic** [comment]
I am not quite sure what DEF file does but let's say I have a method `static void m1(string s)` and I compile the source as a native library. Will this method be available for the application that loads the library? How will it deal with the `string` type? Can I specify how to marshall data types?

**Comment by tonerdo** [comment]
@bazzilic you'll need to apply the `System.Runtime.InteropServices.NativeCallable` attribute to the method you want to export. Here's an example:

```
using System;
using System.Runtime.InteropServices;

namespace csnative
{
    class Program
    {
        [NativeCallable(EntryPoint = "Print", CallingConvention = CallingConvention.StdCall)]
        static int Print()
        {
            Console.WriteLine("Hello from managed code");
            Random random = new Random();
            return random.Next() + 4;
        }

        [NativeCallable(EntryPoint = "GetNum", CallingConvention = CallingConvention.StdCall)]
        public static int GetNum()
        {
            return 15;
        }
    }
}
```

**Comment by bazzilic** [comment]
Is there any documentation on `NativeCallable` attribute? Didn't find much. I am interested in marshalling of classes such as generic containers and such.

**Comment by tonerdo** [comment]
@bazzilic it's no big deal really. I forgot to mention that it's not in the BCL. You create it yourself, like so:

*NativeCallable.cs*

```
namespace System.Runtime.InteropServices
{
    [AttributeUsage(AttributeTargets.Method)]
    public sealed class NativeCallableAttribute : Attribute
    {
        public string EntryPoint;

        public CallingConvention CallingConvention;

        public NativeCallableAttribute()
        {
        }
    }
}
```

**Comment by bazzilic** [comment]
I tried building a DLL on Windows and got this:
```
PS C:\test> dotnet build /t:LinkNative /p:NativeLib=Shared
... standard warnings about imports ...
C:\corert\bin\Windows_NT.x64.Release\build\Microsoft.NETCore.Native.targets(167,5):
error MSB3073: The command "link  @"obj\Debug\netstandard2.0\native\link.rsp""
exited with code 9009. [C:\test\test.csproj]
```

The only code file in the folder, `.\Library.cs`:
```csharp
using System;

namespace aaaa
{
    static class Library
    {
        static byte[] test(byte[] a, byte[] b)
        {
            return new byte[10];
        }
    }
}

namespace System.Runtime.InteropServices
{
    [AttributeUsage(AttributeTargets.Method)]
    public sealed class NativeCallableAttribute : Attribute
    {
        public string EntryPoint;
        public CallingConvention CallingConvention;
        public NativeCallableAttribute() { }
    }
}
```

`test.csproj`:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(MSBuildSDKsPath)\Microsoft.NET.Sdk\Sdk\Sdk.props" />
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <Import Project="$(MSBuildSDKsPath)\Microsoft.NET.Sdk\Sdk\Sdk.targets" />
  <Import Project="$(IlcPath)\build\Microsoft.NETCore.Native.targets" />
</Project>
```

**Comment by tonerdo** [comment]
@bazzilic update your code like so:

`Library.cs`:
```csharp
using System;
using System.Runtime.InteropServices;

namespace aaaa
{
    static class Library
    {
        [NativeCallable(EntryPoint = "test", CallingConvention = CallingConvention.StdCall)]
        static byte[] test(byte[] a, byte[] b)
        {
            return new byte[10];
        }
    }
}
```

`test.csproj`:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(MSBuildSDKsPath)\Microsoft.NET.Sdk\Sdk\Sdk.props" />
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <Import Project="$(MSBuildSDKsPath)\Microsoft.NET.Sdk\Sdk\Sdk.targets" />
  <Import Project="$(IlcPath)\build\Microsoft.NETCore.Native.targets" />
</Project>
```

**Comment by tonerdo** [comment]
@bazzilic I have _finally_ been able to reproduce your error. Looking into it now

**Comment by bazzilic** [comment]
Oh, that's good to hear! I have currently suspended attempts to build a native library, and wrote some code in C. But I am very interested to see this working one day :)

**Comment by tonerdo** [comment]
@bazzilic it should work really soon. It's an Ubuntu specific issue and only happens when you try to build a shared library. Building static libraries works just fine

**Comment by bazzilic** [comment]
Interesting. No idea why ubuntu is so special. Best of luck figuring it out!

**Pull request closed without merging**
